export const KEYWORD_DENSITY_MIN_THRESHOLD = 0.46
export const KEYWORD_DENSITY_MAX_THRESHOLD = 1.1
export const SUB_KEYWORD_DENSITY_MAX_THRESHOLD = 0.9
export const SUB_KEYWORD_DENSITY_MIN_THRESHOLD = 0.12
export const SUB_KEYWORD_DENSITY_VERY_LOW_THRESHOLD = 0.09

export const META_DESCRIPTION_MAX_LENGTH = 160
export const META_DESCRIPTION_DENSITY_MAX_THRESHOLD = 5
export const META_DESCRIPTION_DENSITY_MIN_THRESHOLD = 2

export const TITLE_MAX_LENGTH = 70
export const TITLE_MIN_LENGTH = 40

export const SUB_KEYWORD_META_DESCRIPTION_DENSITY_MAX_THRESHOLD = 5
export const SUB_KEYWORD_META_DESCRIPTION_DENSITY_MIN_THRESHOLD = 2
